[package]
name = "verge_rs_generator"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
openapiv3 = { git = "https://github.com/agily/openapiv3.git" }

